name = "CutDGD"
uuid = "f6ad8f8e-aa95-4eb2-a6f4-7dbdad895a20"
authors = ["Jason Hicken <jason.hicken@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
